content:
  ds:
  - AVLTree: src/ds/AVLTree.cpp
  - BTree: src/ds/BTree.cpp
  - CaptainMo: src/ds/CaptainMo.cpp
  - FenwickTree: src/ds/FenwickTree.cpp
  - LCT: src/ds/LCT.cpp
  - LefitstTree: src/ds/LefitstTree.cpp
  - PersistentSegmentTree: src/ds/PersistentSegmentTree.cpp
  - rbtree-1: src/ds/rbtree-1.cpp
  - RBTree: src/ds/RBTree.cpp
  - RMQ: src/ds/RMQ.cpp
  - RollBackCaptainMo: src/ds/RollBackCaptainMo.cpp
  - SegmentTree: src/ds/SegmentTree.cpp
  - SGTree: src/ds/SGTree.cpp
  - Splay: src/ds/Splay.cpp
  - Treap-dynamic: src/ds/Treap-dynamic.cpp
  - Treap-pointer: src/ds/Treap-pointer.cpp
  - Treap: src/ds/Treap.cpp
  graph:
  - BCC-Edge: src/graph/BCC-Edge.cpp
  - BCC-Point: src/graph/BCC-Point.cpp
  - BiGraphMatch: src/graph/BiGraphMatch.cpp
  - BiWraphMatch: src/graph/BiWraphMatch.cpp
  - BlockForest: src/graph/BlockForest.cpp
  - BlockTree: src/graph/BlockTree.cpp
  - Dijkstra: src/graph/Dijkstra.cpp
  - dsu-on-tree: src/graph/dsu-on-tree.cpp
  - FullyDCP: src/graph/FullyDCP.cpp
  - Graph: src/graph/Graph.cpp
  - GraphMatch: src/graph/GraphMatch.cpp
  - HLD-Edge: src/graph/HLD-Edge.cpp
  - Kosaraju: src/graph/Kosaraju.cpp
  - Kruskal: src/graph/Kruskal.cpp
  - LCA-HLD: src/graph/LCA-HLD.cpp
  - LCA: src/graph/LCA.cpp
  - maxflow: src/graph/maxflow.cpp
  - mincostflow: src/graph/mincostflow.cpp
  - SCC: src/graph/SCC.cpp
  - SPFA: src/graph/SPFA.cpp
  - tree-divide: src/graph/tree-divide.cpp
  - Wraph: src/graph/Wraph.cpp
  - WraphMatch: src/graph/WraphMatch.cpp
  math:
  - 2DGeometry: src/math/2DGeometry.cpp
  - 3DGeometry: src/math/3DGeometry.cpp
  - BSGS: src/math/BSGS.cpp
  - Cipolla: src/math/Cipolla.cpp
  - Combination: src/math/Combination.cpp
  - CRT: src/math/CRT.cpp
  - EulerSeive: src/math/EulerSeive.cpp
  - eval: src/math/eval.cpp
  - EXGCD: src/math/EXGCD.cpp
  - FFT: src/math/FFT.cpp
  - LinearBasis: src/math/LinearBasis.cpp
  - Lucas: src/math/Lucas.cpp
  - Mint: src/math/Mint.cpp
  - Mobius: src/math/Mobius.cpp
  - Modular: src/math/Modular.cpp
  - NTT: src/math/NTT.cpp
  - PollardRho: src/math/PollardRho.cpp
  - poly-struct: src/math/poly-struct.cpp
  - Poly: src/math/Poly.cpp
  - Simplex: src/math/Simplex.cpp
  - SimpsonIntegral: src/math/SimpsonIntegral.cpp
  other:
  - BFPRT: src/other/BFPRT.cpp
  - cpp-header: src/other/cpp-header.cpp
  - debug: src/other/debug.h
  - java-header: src/other/java-header.java
  - SimulateAnneal: src/other/SimulateAnneal.cpp
  string:
  - ACAM: src/string/ACAM.cpp
  - GSAM: src/string/GSAM.cpp
  - KMP: src/string/KMP.cpp
  - Manacher: src/string/Manacher.cpp
  - PAM: src/string/PAM.cpp
  - SA: src/string/SA.cpp
  - SAIS: src/string/SAIS.cpp
  - SAM: src/string/SAM.cpp
  - SqAM: src/string/SqAM.cpp
  - string-hash: src/string/string-hash.cpp
  - Trie: src/string/Trie.cpp
  - ZAlgorithm: src/string/ZAlgorithm.cpp
